SELECT * FROM practice.`HR`;

USE practice;

-- ALTER TABLE `hr analytics dataset` RENAME HR;

ALTER TABLE HR
CHANGE COLUMN ï»¿id emp_id VARCHAR(20) NULL;

DESCRIBE hr;

SELECT * FROM HR;

SET SQL_SAFE_UPDATES = 0;

UPDATE HR
SET BIRTHDATE = CASE
  WHEN BIRTHDATE LIKE '%/%' THEN date_format(str_to_date(BIRTHDATE, '%m/%d/%Y'), '%Y-%m-%d')
  when BIRTHDATE LIKE '%-%' THEN date_format(str_to_date(BIRTHDATE, '%m-%d-%Y'), '%Y-%m-%d')
  ELSE NULL
END;

ALTER TABLE HR
MODIFY COLUMN BIRTHDATE DATE;

UPDATE HR
SET HIRE_DATE = CASE
  WHEN HIRE_DATE LIKE '%/%' THEN date_format(str_to_date(HIRE_DATE, '%m/%d/%Y'), '%Y-%m-%d')
  when HIRE_DATE LIKE '%-%' THEN date_format(str_to_date(HIRE_DATE, '%m-%d-%Y'), '%Y-%m-%d')
  ELSE NULL
END;

SELECT HIRE_DATE FROM HR;

UPDATE HR
SET termdate = IF(termdate IS NOT NULL AND termdate != '', DATE(str_to_date(termdate, '%Y-%m-%d %H:%i:%s UTC')), '0000-00-00')
WHERE TRUE;

SELECT termdate FROM HR;

SET SQL_MODE = 'ALLOW_INVALID_DATES';

ALTER TABLE HR
MODIFY COLUMN TERMDATE DATE;

ALTER TABLE HR
MODIFY COLUMN HIRE_DATE DATE;

DESCRIBE HR;

ALTER TABLE HR ADD COLUMN AGE INT;

UPDATE HR
SET AGE = timestampdiff(YEAR,BIRTHDATE,CURDATE());

SELECT BIRTHDATE, AGE FROM HR;

SELECT 
	MIN(AGE) AS YOUNGEST,
    MAX(AGE) AS OLDEST
FROM HR;

SELECT COUNT(*) FROM HR 
WHERE AGE <18; 

-- GENDER BREAKDOWN OF EMPLOYEES IN THE COMPANY 
SELECT GENDER, COUNT(*) AS COUNT
FROM HR
WHERE AGE >= 18 AND TERMDATE = '0000-00-00'
GROUP BY GENDER;

-- RACE/ETHNICITY BREAKDOEN OF EMPLOYEES IN THE COMPANY 
SELECT RACE, COUNT(*) AS COUNT 
FROM HR 
WHERE AGE >= 18 AND TERMDATE = '0000-00-00'
GROUP BY RACE
ORDER BY COUNT(*) DESC;

-- AGE DISTRIBUTION OF EMPLOYEES IN THE COMPANY
SELECT 
	MIN(AGE) AS YOUNGEST,
    MAX(AGE) AS OLDEST
FROM HR 
WHERE AGE >=18 AND TERMDATE ='0000-00-00';

SELECT 
	CASE
		WHEN AGE >=18 AND AGE <= 24 THEN '18-24'
        WHEN AGE >=25 AND AGE <= 34 THEN '25-34'
        WHEN AGE >=35 AND AGE <= 44 THEN '35-44'
        WHEN AGE >=45 AND AGE <= 54 THEN '44-54'
        WHEN AGE >=55 AND AGE <= 64 THEN '55-64'
        ELSE '65+'
	END AS AGE_GROUP,
    COUNT(*) AS COUNT
FROM HR 
WHERE AGE >= 18 AND TERMDATE ='0000-00-00'
GROUP BY AGE_GROUP
ORDER BY AGE_GROUP;

SELECT 
	CASE
		WHEN AGE >=18 AND AGE <= 24 THEN '18-24'
        WHEN AGE >=25 AND AGE <= 34 THEN '25-34'
        WHEN AGE >=35 AND AGE <= 44 THEN '35-44'
        WHEN AGE >=45 AND AGE <= 54 THEN '44-54'
        WHEN AGE >=55 AND AGE <= 64 THEN '55-64'
        ELSE '65+'
	END AS AGE_GROUP, GENDER,
    COUNT(*) AS COUNT
FROM HR 
WHERE AGE >= 18 AND TERMDATE ='0000-00-00'
GROUP BY AGE_GROUP,GENDER
ORDER BY AGE_GROUP,GENDER;

--  HOW MANY EMPLOYEES WORK AT HEADQUARTERS VERSUS REMOTE LOCATIONS 
SELECT LOCATION, COUNT(*) AS COUNT
FROM HR
WHERE AGE >= 18 AND TERMDATE = '0000-00-00'
GROUP BY LOCATION;

-- AVERAGE LENGTH OF EMPLOYMENT FOR EMPLOYEES WHO HAVE BEEN TERMINATED 
SELECT 
	ROUND(AVG(DATEDIFF(TERMDATE,HIRE_DATE))/365,0) AS AVG_LENGTH_EMPLOYMENT
FROM HR 
WHERE TERMDATE <= CURDATE() AND TERMDATE <> '0000-00-00' AND AGE >= 18;

-- HOW DOES THE GENDER DISTRIBUTION VARY ACROSS DEPARTMENTS AND JOB TITLES 
SELECT DEPARTMENT,GENDER,COUNT(*) AS COUNT
FROM HR
WHERE AGE>= 18 AND TERMDATE ='0000-00-00'
GROUP BY DEPARTMENT, GENDER
ORDER BY DEPARTMENT;

-- DISTRIBUTION OF JOB TITLES ACROSS THE COMPANY
SELECT JOBTITLE,COUNT(*) AS COUNT
FROM HR
WHERE AGE>= 18 AND TERMDATE ='0000-00-00'
GROUP BY JOBTITLE
ORDER BY JOBTITLE DESC;

-- WHICH DEPARTMENT HAS THE HIGHEST TURNOVER RATE
SELECT DEPARTMENT, TOTAL_COUNT,TERMINATED_COUNT,TERMINATED_COUNT/TOTAL_COUNT AS TERMINATION_RATE
FROM(
	SELECT DEPARTMENT, 
    COUNT(*) AS TOTAL_COUNT,
    SUM(CASE WHEN TERMDATE <> '0000-00-00' AND TERMDATE <= CURDATE() THEN 1 ELSE 0 END ) AS TERMINATED_COUNT
    FROM HR 
    WHERE AGE>= 18
    GROUP BY DEPARTMENT) AS SUBQUERY 
ORDER BY TERMINATION_RATE DESC;
    
-- DISTRIBUTION OF EMPLOYEES ACROSS LOCATIONS BY CITY AND STATE
SELECT LOCATION_STATE,COUNT(*) AS COUNT
FROM HR
WHERE AGE>= 18 AND TERMDATE ='0000-00-00'
GROUP BY LOCATION_STATE
ORDER BY COUNT DESC;

-- HOW HAS THE COMPANY'S EMPLOYEE COUNT CHANGED OVER TIME BASED ON HIRE AND TERM DATES 
SELECT YEAR, HIRES, TERMINATIONS, HIRES-TERMINATIONS AS NET_CHANGE, ROUND((HIRES-TERMINATIONS)/HIRES * 100,2) AS NET_CHANGE_PERCENT
FROM(
	SELECT YEAR(HIRE_DATE) AS YEAR,
    COUNT(*) AS HIRES,
    SUM(CASE WHEN TERMDATE <> '0000-00-00' AND  TERMDATE <= CURDATE() THEN 1 ELSE 0 END ) AS TERMINATIONS
    FROM HR
    WHERE AGE>= 18 
    GROUP BY YEAR(HIRE_DATE)) AS SUBQUERY
ORDER BY YEAR ASC;

-- WHAT IS THE TENURE DISTRIBUTION FOR EACH DEPARTMENT
SELECT DEPARTMENT, ROUND(AVG(DATEDIFF(TERMDATE, HIRE_DATE)/365),0) AS AVG_TENURE
FROM HR
WHERE TERMDATE <= CURDATE() AND TERMDATE<> '0000-00-00' AND AGE >= 18
GROUP BY DEPARTMENT;

















